rootProject.name = 'food-ordering-system'

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        maven {
            url "https://packages.confluent.io/maven/"
        }
    }
}

includeBuild('build-logic')

include 'order-service'
include 'order-service:order-domain'
include 'order-service:order-application'
include 'order-service:order-data-access'
include 'order-service:order-messaging'
include 'order-service:order-container'
include 'order-service:order-domain:order-domain-core'
include 'order-service:order-domain:order-application-service'
include 'common'
include 'common:common-domain'
include 'infrastructure'
include 'infrastructure:kafka'
include 'infrastructure:kafka:kafka-producer'
include 'infrastructure:kafka:kafka-consumer'
include 'infrastructure:kafka:kafka-model'
include 'infrastructure:kafka:kafka-config-data'
include 'common:common-application'
include 'customer-service'
include 'restaurant-service'
include 'payment-service'
include 'payment-service:payment-container'
include 'payment-service:payment-data-access'
include 'payment-service:payment-messaging'
include 'payment-service:payment-domain'
include 'payment-service:payment-domain:payment-domain-core'
include 'payment-service:payment-domain:payment-application-service'
include 'restaurant-service:restaurant-container'
include 'restaurant-service:restaurant-data-access'
include 'restaurant-service:restaurant-domain'
include 'restaurant-service:restaurant-domain:restaurant-application-service'
include 'restaurant-service:restaurant-domain:restaurant-domain-core'
include 'restaurant-service:restaurant-messaging'
include 'common:common-data-access'
include 'common:common-mapper'
include 'infrastructure:saga'
include 'infrastructure:outbox'
include 'common:common-data-access-archive'
include 'customer-service:customer-application'
include 'customer-service:customer-container'
include 'customer-service:customer-data-access'
include 'customer-service:customer-messaging'
include 'customer-service:customer-domain'
include 'customer-service:customer-domain:customer-domain-core'
include 'customer-service:customer-domain:customer-application-service'