plugins {
    id 'common-library-convention'
    id 'spring-library-convention'
    id 'apache-avro-library-convention'
    id 'logging-library-convention'
}

tasks.bootJar {
    enabled = false
}

dependencies {
    implementation project(':common:kafka:kafka-config-data')
    implementation project(':common:kafka:kafka-consumer')
    implementation project(':common:kafka:kafka-model')
    implementation project(':common:kafka:kafka-producer')
    implementation project(':order-service:order-domain:order-application-service')
    implementation project(':common:common-mapper')
    implementation project(':common:common-message')
    implementation project(':common:outbox')
    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.postgresql:postgresql'

    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
}