plugins {
    id 'common-library-convention'
    id 'spring-library-convention'
}

tasks.bootJar {
    enabled = false
}

dependencies {
    implementation project(':infrastructure:kafka:kafka-config-data')
    implementation project(':infrastructure:kafka:kafka-consumer')
    implementation project(':infrastructure:kafka:kafka-model')
    implementation project(':infrastructure:kafka:kafka-producer')
    implementation project(':order-service:order-domain:order-domain-core')
    implementation project(':common:common-domain')
}