plugins {
    id 'common-library-convention'
    id 'logging-library-convention'
    id 'spring-library-convention'
}

tasks.bootJar {
    enabled = false
}

dependencies {
    implementation project(':order-service:order-domain:order-application-service')
    implementation project(':order-service:order-ai')
    implementation project(':common:common-application')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'

    testImplementation 'org.springframework.boot:spring-boot-starter-webmvc-test'
}