replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: com.food.ordering.system/order.service
  tag: "1.0-SNAPSHOT"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8181

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 1Gi

datasource:
  url: jdbc:postgresql://postgres:5432/postgres?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
  username: postgres
  password: admin

kafka:
  bootstrapServers: broker-1:19092,broker-2:19092,broker-3:19092
  schemaRegistryUrl: http://schema-registry:8081

extraEnv: {}

nodeSelector: {}
tolerations: []
affinity: {}
