replicaCount: 1

nameOverride: ""
fullnameOverride: ""

image:
  repository: com.food.ordering.system/order.service
  tag: "1.0-SNAPSHOT"
  pullPolicy: IfNotPresent

imagePullSecrets: []

service:
  type: ClusterIP
  port: 8181
  managementPort: 9090

resources:
  requests:
    cpu: 100m
    memory: 512Mi
  limits:
    memory: 1Gi

datasource:
  url: jdbc:postgresql://host.minikube.internal:5432/postgres?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
  username: postgres
  password: admin

kafka:
  bootstrapServers: host.minikube.internal:29094,host.minikube.internal:39094,host.minikube.internal:49094
  schemaRegistryUrl: http://host.minikube.internal:8081

extraEnv: {}

nodeSelector: {}
tolerations: []
affinity: {}
