plugins {
    id 'common-library-convention'
    id 'spring-library-convention'
    id 'apache-avro-library-convention'
}

dependencies {
    implementation project(':common:kafka:kafka-model')
    implementation project(':common:kafka:kafka-config-data')
    implementation project(':common:outbox')
    implementation project(':order-service:order-domain:order-domain-core')
    implementation project(':common:common-domain')

    implementation 'org.springframework.kafka:spring-kafka'
    implementation 'org.springframework.boot:spring-boot-starter-jackson'
    compileOnly libs.lombok
    annotationProcessor libs.lombok
}