plugins {
    id 'common-library-convention'
    id 'logging-library-convention'
    id 'spring-library-convention'
}

dependencies {
    api project(':order-service:order-domain:order-domain-core')
    api project(':common:common-domain')
    implementation project(':common:common-mapper')
    api project(':infrastructure:saga')
    api project(':infrastructure:outbox')

    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework:spring-tx'
    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
    implementation 'org.springframework.boot:spring-boot-starter-jackson'
}