plugins {
    id 'common-library-convention'
    id 'logging-library-convention'
    id 'spring-library-convention'
}

tasks.bootJar {
    enabled = false
}

dependencies {
    implementation project(':common:common-domain')

    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
}