plugins {
    id 'common-library-convention'
    id 'logging-library-convention'
    id 'spring-library-convention'
}

dependencies {
    implementation project(':customer-service:customer-domain:customer-application-service')
    implementation project(':customer-service:customer-domain:customer-domain-core')
    implementation project(':common:common-data-access')
    implementation project(':common:common-domain')
    implementation project(':common:common-mapper')
    implementation project(':infrastructure:outbox')
    implementation project(':common:common-data-access-archive')

    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor

    implementation 'org.springframework.boot:spring-boot-starter-data-jpa'
    implementation 'org.postgresql:postgresql'
}