plugins {
    id 'common-library-convention'
    id 'logging-library-convention'
    id 'spring-library-convention'
}

tasks.bootJar {
    enabled = false
}

dependencies {
    implementation project(':customer-service:customer-domain:customer-application-service')
    implementation project(':common:common-application')
    implementation project(':customer-service:customer-domain:customer-domain-core')
    implementation project(':common:common-domain')

    implementation 'org.springframework.boot:spring-boot-starter-web'
    implementation 'org.springframework.boot:spring-boot-starter-validation'
}