apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "food-ordering-service.fullname" . }}
  labels:
    {{- include "food-ordering-service.labels" . | nindent 4 }}
data:
  SERVER_PORT: {{ .Values.service.port | quote }}
  PORT: {{ .Values.service.port | quote }}
  SPRING_DATASOURCE_URL: {{ .Values.datasource.url | quote }}
  SPRING_DATASOURCE_USERNAME: {{ .Values.datasource.username | quote }}
  KAFKA_CONFIG_BOOTSTRAP_SERVERS: {{ .Values.kafka.bootstrapServers | quote }}
  KAFKA_CONFIG_SCHEMA_REGISTRY_URL: {{ .Values.kafka.schemaRegistryUrl | quote }}
  {{- range $key, $value := .Values.extraEnv }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
