ingress:
  enabled: true
  className: nginx
  annotations: {}

order-service:
  replicaCount: 2
  fullnameOverride: order-service
  image:
    repository: com.food.ordering.system/order.service
    tag: "1.0-SNAPSHOT"
    pullPolicy: IfNotPresent
  service:
    port: 8181
  datasource:
    url: jdbc:postgresql://host.minikube.internal:5432/postgres?currentSchema=order&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
  kafka:
    bootstrapServers: host.minikube.internal:29094,host.minikube.internal:39094,host.minikube.internal:49094
    schemaRegistryUrl: http://host.minikube.internal:8081
  extraEnv:
    SPRING_AI_OLLAMA_BASE_URL: http://host.minikube.internal:11434

payment-service:
  replicaCount: 2
  fullnameOverride: payment-service
  image:
    repository: com.food.ordering.system/payment.service
    tag: "1.0-SNAPSHOT"
    pullPolicy: IfNotPresent
  service:
    port: 8182
  datasource:
    url: jdbc:postgresql://host.minikube.internal:5432/postgres?currentSchema=payment&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
  kafka:
    bootstrapServers: host.minikube.internal:29094,host.minikube.internal:39094,host.minikube.internal:49094
    schemaRegistryUrl: http://host.minikube.internal:8081

restaurant-service:
  replicaCount: 2
  fullnameOverride: restaurant-service
  image:
    repository: com.food.ordering.system/restaurant.service
    tag: "1.0-SNAPSHOT"
    pullPolicy: IfNotPresent
  service:
    port: 8183
  datasource:
    url: jdbc:postgresql://host.minikube.internal:5432/postgres?currentSchema=restaurant&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
  kafka:
    bootstrapServers: host.minikube.internal:29094,host.minikube.internal:39094,host.minikube.internal:49094
    schemaRegistryUrl: http://host.minikube.internal:8081

customer-service:
  replicaCount: 2
  fullnameOverride: customer-service
  image:
    repository: com.food.ordering.system/customer.service
    tag: "1.0-SNAPSHOT"
    pullPolicy: IfNotPresent
  service:
    port: 8184
  datasource:
    url: jdbc:postgresql://host.minikube.internal:5432/postgres?currentSchema=customer&binaryTransfer=true&reWriteBatchedInserts=true&stringtype=unspecified
    username: postgres
    password: admin
  kafka:
    bootstrapServers: host.minikube.internal:29094,host.minikube.internal:39094,host.minikube.internal:49094
    schemaRegistryUrl: http://host.minikube.internal:8081
