plugins {
    id 'common-library-convention'
    id 'logging-library-convention'
    id 'spring-library-convention'
}

dependencies {
    api project(':restaurant-service:restaurant-domain:restaurant-domain-core')
    implementation project(':common:common-mapper')
    implementation project(':common:saga')
    implementation project(':common:outbox')

    implementation 'org.springframework.boot:spring-boot-starter-validation'
    implementation 'org.springframework:spring-tx'
    implementation 'org.springframework.boot:spring-boot-starter-jackson'

    implementation libs.mapstruct
    annotationProcessor libs.mapstruct.processor
}